### ISSUE TITLE
Version 1 TODO list

### ISSUE THREAD

**Issue by binarman** [binarman/esp32-counter#1]
- [x] implement short history autoscroll
- [x] implement menu screen
- [x] implement full history screen
- [x] check power consumption, use low power modes
  - Wrover at 240 MHz consumes ~70 mA (5v)
  - Wrover at 80 MHz consumes ~63 mA (5v)
  - Wrover at 80 Mhz + periodical light sleep mode ~50 mA (5v) 
- [x] wrap widgets in containers (screen)
  - [x] create basic screen class and group widgets in them
- [x] replace magic numbers with descriptive constants
- [x] implement battery indicator
- [x] implement adaptive counter size
- [x] cleanup
  - [x] code formatting
  - [x] create specific class for every screen
  - [x] prepare basic documentation about architecture and screen connections
